version: 2
updates:
  # Maintain dependencies for the backend (Node.js)
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain dependencies for the frontend (Node.js)
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
